import { Check, ChevronRight, CircleUserRound, SlidersHorizontal, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';

export default function Settings() {
  const [name, setName] = useState('');
  const [course, setCourse] = useState('');
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const profile = JSON.parse(localStorage.getItem('projectpilot-profile') || '{}'); setName(profile.name || ''); setCourse(profile.course || ''); } catch { /* empty profile */ } }, []);
  const save = () => { localStorage.setItem('projectpilot-profile', JSON.stringify({ name, course })); setSaved(true); setTimeout(() => setSaved(false), 2200); };
  return <div className="page-enter mx-auto max-w-4xl px-6 py-10 md:px-12 md:py-14"><div className="border-b border-border pb-9"><p className="mono text-[10px] uppercase tracking-[.2em] text-destructive">Workspace / 03</p><h1 className="display mt-3 text-5xl font-semibold md:text-7xl">Preferences.</h1><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">Make the studio sound like you. These details stay in your browser and shape your next session.</p></div><div className="mt-10 grid gap-5 md:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-border bg-card p-6 md:p-8"><div className="mb-8 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent"><CircleUserRound size={19} /></span><div><p className="mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Your profile</p><h2 className="display text-2xl font-semibold">A little context.</h2></div></div><label className="mb-2 block text-sm font-bold">Name</label><input value={name} onChange={(e) => setName(e.target.value)} placeholder="What should we call you?" className="mb-6 w-full rounded-xl border border-input bg-background p-3.5 text-sm outline-none focus:border-foreground" data-testid="input-profile-name" /><label className="mb-2 block text-sm font-bold">Course or discipline</label><input value={course} onChange={(e) => setCourse(e.target.value)} placeholder="e.g. Interaction Design, Computer Science" className="w-full rounded-xl border border-input bg-background p-3.5 text-sm outline-none focus:border-foreground" data-testid="input-profile-course" /><button onClick={save} className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground" data-testid="button-save-settings">{saved ? <Check size={15} /> : null}{saved ? 'Saved' : 'Save preferences'}</button></section><aside className="space-y-5"><div className="rounded-2xl bg-primary p-6 text-primary-foreground"><SlidersHorizontal size={19} className="text-accent" /><h2 className="display mt-8 text-3xl font-semibold">Good constraints make good work.</h2><p className="mt-3 text-sm leading-6 text-primary-foreground/65">When you generate, be honest about time, tools, and access. The best project is the one you can show working.</p></div><div className="rounded-2xl border border-border bg-secondary/45 p-6"><Sparkles size={18} className="text-destructive" /><h2 className="mt-4 font-bold">Pilot principle</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Clarity is not playing small. It is making your ambition legible.</p><div className="mt-5 flex items-center gap-2 text-xs font-bold">Read the approach <ChevronRight size={14} /></div></div></aside></div></div>;
}